version: '2'
services: 
    api2:
        image: 'noalgalex/node-api2:latest'
    api2lb:
        image: 'dockercloud/haproxy:latest'
        links:
            - 'api2'
        ports:
            - '85:80'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock