version: '2'
services:
  api1:
    image: 'noalgalex/node-api1:latest'
  api1lb:
    image: 'dockercloud/haproxy:latest'
    links:
      - api1
    ports:
      - '80:80'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock